### ISSUE TITLE
无法加载此插件，并且已尝试多个版本

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [XiaMoZhiShi/MorphPlugin#13]
服务端是Mohist version 1.20.1-604 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.2.20, NeoForge version 47.1.79)
<img width="866" alt="image" src="https://github.com/XiaMoZhiShi/FeatherMorph/assets/141799770/0b3ab45c-bc7e-4c72-a779-2ae927900a12">
[09:11:31 INFO]: [FeatherMorph] Enabling FeatherMorph v0.12.16
[09:11:31 ERROR]: 初始化xiamomc.morph.events.PlayerTracker@380848cf失败: io/papermc/paper/event/player/PlayerArmSwingEvent
[09:11:31 WARN]: java.lang.NoClassDefFoundError: io/papermc/paper/event/player/PlayerArmSwingEvent
[09:11:31 WARN]:        at TRANSFORMER/forge@47.2.20/com.mohistmc.bukkit.remapping.ClassLoaderRemapper.tryDefineClass(ClassLoaderRemapper.java:172)
[09:11:31 WARN]:        at TRANSFORMER/forge@47.2.20/com.mohistmc.bukkit.remapping.ReflectionHandler_8.redirectGetDeclaredMethods(ReflectionHandler.java:47)
[09:11:31 WARN]:        at xiamomc.morph.shaded.pluginbase.PluginObject.addInitializerMethods(PluginObject.java:53)
[09:11:31 WARN]:        at xiamomc.morph.shaded.pluginbase.PluginObject.initialDependencyResolve(PluginObject.java:90)
[09:11:31 WARN]:        at xiamomc.morph.shaded.pluginbase.PluginObject.<init>(PluginObject.java:46)
[09:11:31 WARN]:        at xiamomc.morph.MorphPluginObject.<init>(MorphPluginObject.java:5)
[09:11:31 WARN]:        at xiamomc.morph.events.PlayerTracker.<init>(PlayerTracker.java:28)
[09:11:31 WARN]:        at xiamomc.morph.MorphPlugin.onEnable(MorphPlugin.java:102)
[09:11:31 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347)
[09:11:31 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
[09:11:31 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482)
[09:11:31 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549)
[09:11:31 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462)
[09:11:31 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441)
[09:11:31 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341)
[09:11:31 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224)
[09:11:31 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850)
[09:11:31 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
[09:11:31 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
>
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "sentry-pool-1-thread-1"
[09:11:32 ERROR]: Error occurred while enabling FeatherMorph v0.12.16 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.key.Key org.bukkit.attribute.Attribute.key()'
        at xiamomc.morph.abilities.options.AttributeModifyOption.from(AttributeModifyOption.java:31) ~[?:?]
        at xiamomc.morph.skills.DefaultConfigGenerator.lambda$addAbilityConfigurations$17(DefaultConfigGenerator.java:227) ~[?:?]
        at xiamomc.morph.skills.DefaultConfigGenerator.addAbilityConfiguration(DefaultConfigGenerator.java:97) ~[?:?]
        at xiamomc.morph.skills.DefaultConfigGenerator.addAbilityConfiguration(DefaultConfigGenerator.java:106) ~[?:?]
        at xiamomc.morph.skills.DefaultConfigGenerator.addAbilityConfigurations(DefaultConfigGenerator.java:224) ~[?:?]
        at xiamomc.morph.skills.DefaultConfigGenerator.getDefaultSkillConfiguration(DefaultConfigGenerator.java:136) ~[?:?]
        at xiamomc.morph.storage.skill.SkillAbilityConfigurationStore.createDefault(SkillAbilityConfigurationStore.java:56) ~[?:?]
        at xiamomc.morph.storage.skill.SkillAbilityConfigurationStore.createDefault(SkillAbilityConfigurationStore.java:30) ~[?:?]
        at xiamomc.morph.shaded.pluginbase.JsonBasedStorage.<init>(JsonBasedStorage.java:34) ~[?:?]
        at xiamomc.morph.storage.MorphJsonBasedStorage.<init>(MorphJsonBasedStorage.java:6) ~[?:?]
        at xiamomc.morph.storage.skill.SkillAbilityConfigurationStore.<init>(SkillAbilityConfigurationStore.java:30) ~[?:?]
        at xiamomc.morph.MorphPlugin.onEnable(MorphPlugin.java:132) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
[09:11:32 INFO]: [FeatherMorph] Disabling FeatherMorph v0.12.16
[09:11:32 ERROR]: 无法保存数据存储的配置: Cannot invoke "java.io.File.exists()" because "this.configurationFile" is null
[09:11:32 WARN]: Error occurred while disabling: java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "this.configurationFile" is null
[09:11:32 WARN]: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "this.configurationFile" is null
[09:11:32 WARN]:        at xiamomc.morph.shaded.pluginbase.JsonBasedStorage.saveConfiguration(JsonBasedStorage.java:147)
[09:11:32 WARN]:        at xiamomc.morph.MorphManager.saveConfiguration(MorphManager.java:1361)
[09:11:32 WARN]:        at xiamomc.morph.MorphManager.onPluginDisable(MorphManager.java:1169)
[09:11:32 WARN]:        at xiamomc.morph.MorphPlugin.onDisable(MorphPlugin.java:176)
[09:11:32 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349)
[09:11:32 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:365)
[09:11:32 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:507)
[09:11:32 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[09:11:32 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482)
[09:11:32 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549)
[09:11:32 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462)
[09:11:32 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441)
[09:11:32 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341)
[09:11:32 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224)
[09:11:32 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850)
[09:11:32 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
[09:11:32 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[09:11:32 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "this.configurationFile" is null
[09:11:32 WARN]:        at xiamomc.morph.shaded.pluginbase.JsonBasedStorage.saveConfiguration(JsonBasedStorage.java:131)
[09:11:32 WARN]:        ... 16 more

**Comment by MATRIX-feather** [comment]
```
[09:11:31 WARN]: java.lang.NoClassDefFoundError: io/papermc/paper/event/player/PlayerArmSwingEvent
```
FeatherMorph依赖PaperAPI，但你使用的Mohist版本似乎并没有完整实现。
我这边暂时无法对Mod端提供支持，可以试试去Mohist那边开一个issue描述这个问题，看看他们能不能解决
