### ISSUE TITLE
Feature: force disguised mobs in config file

### ISSUE THREAD

**Issue by AnterCreeper** [XiaMoZhiShi/MorphPlugin#2]

**Comment by AnterCreeper** [comment]
player becomes one mob once login in and forever

**Comment by MATRIX-feather** [comment]
给我一两周研究一下，我试试看能不能做出来（

**Comment by MATRIX-feather** [comment]
试试看[#634构建](https://github.com/XiaMoZhiShi/FeatherMorph/actions/runs/5917405195)？

在配置里把`forced_disguise`改成你想要而且能伪装的ID然后重载就好

**Comment by AnterCreeper** [comment]
[15:42:46] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 15, column 20:
      forced_disguise: @none
                       ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:338) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:181) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at xiamomc.morph.shaded.pluginbase.Configuration.PluginConfigManager.reload(PluginConfigManager.java:167) ~[FeatherMorph-0.12.6-1.jar:?]
	at xiamomc.morph.config.MorphConfigManager.reload(MorphConfigManager.java:129) ~[FeatherMorph-0.12.6-1.jar:?]
	at xiamomc.morph.shaded.pluginbase.Configuration.PluginConfigManager.<init>(PluginConfigManager.java:27) ~[FeatherMorph-0.12.6-1.jar:?]
	at xiamomc.morph.config.MorphConfigManager.<init>(MorphConfigManager.java:22) ~[FeatherMorph-0.12.6-1.jar:?]
	at xiamomc.morph.MorphPlugin.onEnable(MorphPlugin.java:129) ~[FeatherMorph-0.12.6-1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-49]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-49]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-49]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-49]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-49]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-49]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-49]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-49]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-49]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 15, column 20:
      forced_disguise: @none
                       ^

**Comment by AnterCreeper** [comment]
另外，客户端mod不显示生物皮肤

**Comment by MATRIX-feather** [comment]
配置加载在后面的构建里修复了

客户端不显示皮肤的生物具体有哪些？我稍后集中修复一下

**Comment by AnterCreeper** [comment]
没有一一测试
目前只有zombie😂

1.僵尸溺尸转化之类的？(optional)
2.盔甲值？(optional)

3.自己的皮肤以及其他玩家的皮肤显示(正版)
4.仇恨据伙伴说有点问题？我暂时没有复现

**Comment by AnterCreeper** [comment]
太感谢了！

**Comment by MATRIX-feather** [comment]
僵尸转化溺尸这个我会考虑在后面的版本实装

盔甲值可以通过改`skills.json`实现，参考一下铁傀儡那段是怎么写的（

皮肤显示可能是LD那边对玩家伪装处理的有问题，我这里也是第一次变的时候别人看没皮肤，之后就好了

仇恨是因为最近版本实装了暴露值系统，可以暂时通过`/fm option revealing f`禁用，等我过几天发新客户端模组就能显示出来了

（不过僵尸有变种皮肤的嘛？）
