### ISSUE TITLE
An error occurred while applying disguise

### ISSUE THREAD

**Issue by BluAxoVR** [XiaMoZhiShi/MorphPlugin#20]
When I try to morph/disguise it says "An error occurred while applying disguise" I only have the plugin installed and client mod

**Comment by BluAxoVR** [comment]
[23:25:01 ERROR]: [FeatherMorph] Error while disguising: Null value for attribute 'identifier'!
[23:25:01 WARN]: java.lang.NullPointerException: Null value for attribute 'identifier'!
[23:25:01 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.backends.DisguiseWrapper.read(DisguiseWrapper.java:393)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.backends.fallback.NilBackend.disguise(NilBackend.java:135)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.MorphManager.buildDisguise(MorphManager.java:861)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.MorphManager.doDisguise(MorphManager.java:645)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.MorphManager.morph(MorphManager.java:607)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.network.server.MorphClientHandler.onMorphCommand(MorphClientHandler.java:670)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.network.commands.C2S.C2SMorphCommand.onCommand(C2SMorphCommand.java:25)
[23:25:01 WARN]:        at FeatherMorph-1.1.0-beta.6-all.jar//xiamomc.morph.network.server.MorphClientHandler.lambda$load$6(MorphClientHandler.java:251)
[23:25:01 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[23:25:01 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:197)
[23:25:01 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26)
[23:25:01 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13)
[23:25:01 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36)
[23:25:01 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:25:01 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[23:25:01 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[23:25:01 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478)
[23:25:01 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[23:25:01 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[23:25:01 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456)
[23:25:01 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449)
[23:25:01 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[23:25:01 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558)
[23:25:01 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246)
[23:25:01 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[23:25:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by MATRIX-feather** [comment]
Please try if the latest build solves this issue: https://github.com/XiaMoZhiShi/FeatherMorph/actions/runs/9728428130

Also using the client renderer is not recommended because it's half-broken now. You might want to install ProtocolLib to use the server renderer for a better experience
