### ISSUE TITLE
folia 报错

### ISSUE THREAD

**Issue by xiaoluofa** [XiaMoZhiShi/MorphPlugin#8]
[FeatherMorph] Unhandled exception number 1024 occurred in onPacketSending(PacketEvent) for FeatherMorph
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2832) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:2246) ~[?:?]
        at xiamomc.morph.backends.server.renderer.network.listeners.ProtocolListener.getNmsEntityFrom(ProtocolListener.java:56) ~[FeatherMor
ph-1.0.7-folia.jar:?]
        at xiamomc.morph.backends.server.renderer.network.listeners.MetaPacketListener.onMetaPacket(MetaPacketListener.java:44) ~[FeatherMor
ph-1.0.7-folia.jar:?]
        at xiamomc.morph.backends.server.renderer.network.listeners.MetaPacketListener.onPacketSending(MetaPacketListener.java:38) ~[Feather
Morph-1.0.7-folia.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib .
jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[Protoco
lLib .jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:160) ~[ProtocolLib .ja
r:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib .ja
r:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolL
ib .jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib .
jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib
 .jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib .jar:?
]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib .jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection$PacketSendAction.lambda$new$0(Connection.java:1043) ~[?:?]
        at net.minecraft.network.Connection$WrappedConsumer.accept(Connection.java:1027) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:590) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:547) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:438) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:295) ~[luminol-1.20.4.jar:gi
t-Luminol-"59a428e"]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:280) ~[luminol-1.20.4.jar:gi
t-Luminol-"59a428e"]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:285) ~[ProtocolLib
.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59)
 ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:183) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.async.AsyncMarker.sendPacket(AsyncMarker.java:388) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.async.PacketSendingQueue.sendPacket(PacketSendingQueue.java:276) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.async.PacketSendingQueue.processPacketHolder(PacketSendingQueue.java:219) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.async.PacketSendingQueue.trySendPackets(PacketSendingQueue.java:140) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.async.PacketSendingQueue.signalPacketUpdate(PacketSendingQueue.java:102) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.async.AsyncFilterManager.signalPacketTransmission(AsyncFilterManager.java:437) ~[ProtocolLib .jar:?]
        at com.comphenix.protocol.async.AsyncFilterManager.signalPacketTransmission(AsyncFilterManager.java:397) ~[ProtocolLib .jar:?]
        at net.imprex.orebfuscator.obfuscation.ObfuscationListenerAsync.postChunkProcessing(ObfuscationListenerAsync.java:37) ~[orebfuscator
-plugin-5.4.3.jar:?]
        at net.imprex.orebfuscator.obfuscation.ObfuscationListener.complete(ObfuscationListener.java:139) ~[orebfuscator-plugin-5.4.3.jar:?]
        at net.imprex.orebfuscator.obfuscation.ObfuscationListener.lambda$onPacketSending$1(ObfuscationListener.java:101) ~[orebfuscator-plu
gin-5.4.3.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.complete(ObfuscationRequest.java:72) ~[orebfuscator-plugin-5.4.3.jar:?]
        at net.imprex.orebfuscator.cache.ObfuscationCache.lambda$get$0(ObfuscationCache.java:65) ~[orebfuscator-plugin-5.4.3.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by xiaoluofa** [comment]
指令无法使用

**Comment by xiaoluofa** [comment]
同时mod也无法识别

**Comment by MATRIX-feather** [comment]
我这里无法复现，可以提供问题发生的全过程吗？

---
edit: 我这里用Modrinth上的1.0.7Folia版本，外加ProtocolLib [build#679](https://ci.dmulloy2.net/job/ProtocolLib/679)和[676](https://ci.dmulloy2.net/job/ProtocolLib/676)，并没有出现描述中的情况：<br>
![image](https://github.com/XiaMoZhiShi/FeatherMorph/assets/55654482/bc7165c9-3dc0-48bd-a235-17f3433ad39a)

**Comment by xiaoluofa** [comment]
> 我这里无法复现，可以提供问题发生的全过程吗？
> 
> edit: 我这里用Modrinth上的1.0.7Folia版本，外加ProtocolLib [build#679](https://ci.dmulloy2.net/job/ProtocolLib/679)和[676](https://ci.dmulloy2.net/job/ProtocolLib/676)，并没有出现描述中的情况： ![image](https://private-user-images.githubusercontent.com/55654482/307824790-bc7165c9-3dc0-48bd-a235-17f3433ad39a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODk1MzUsIm5iZiI6MTcwOTA4OTIzNSwicGF0aCI6Ii81NTY1NDQ4Mi8zMDc4MjQ3OTAtYmM3MTY1YzktM2RjMC00OGJkLWEyMzUtMTdmMzQzM2FkMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAzMDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDRmNmVmYWM3YTI3Njc1Njk0N2E4ODkxOWYxZTA0N2M3NzdmMTUyODg2NDFiNGRiODAwYTE3ZTAzYzI0NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m0rFVeY86d8cibuMG6fecRhOt3nd1Uaadf0vzUFjrj0)

收到，我今天测试一下你这个版本

**Comment by xiaoluofa** [comment]
> 我这里无法复现，可以提供问题发生的全过程吗？
> 
> edit: 我这里用Modrinth上的1.0.7Folia版本，外加ProtocolLib [build#679](https://ci.dmulloy2.net/job/ProtocolLib/679)和[676](https://ci.dmulloy2.net/job/ProtocolLib/676)，并没有出现描述中的情况： ![image](https://private-user-images.githubusercontent.com/55654482/307824790-bc7165c9-3dc0-48bd-a235-17f3433ad39a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDI3OTEsIm5iZiI6MTcwOTEwMjQ5MSwicGF0aCI6Ii81NTY1NDQ4Mi8zMDc4MjQ3OTAtYmM3MTY1YzktM2RjMC00OGJkLWEyMzUtMTdmMzQzM2FkMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA2NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ODc4NzhkY2ViMDBkYjYxZDBhNjY4Nzg3OTM4NTNhNGFkZDY2ZTQ1Y2E0MjdjMzU4ZGYwYTUzMTBjMzExYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.21Mf7PuF59om9l-Y1DcEAoOjVXIzkcOJgufa-Onis2M)

笑死我是678

**Comment by MATRIX-feather** [comment]
> > 我这里无法复现，可以提供问题发生的全过程吗？
> > edit: 我这里用Modrinth上的1.0.7Folia版本，外加ProtocolLib [build#679](https://ci.dmulloy2.net/job/ProtocolLib/679)和[676](https://ci.dmulloy2.net/job/ProtocolLib/676)，并没有出现描述中的情况： ![image](https://private-user-images.githubusercontent.com/55654482/307824790-bc7165c9-3dc0-48bd-a235-17f3433ad39a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDI3OTEsIm5iZiI6MTcwOTEwMjQ5MSwicGF0aCI6Ii81NTY1NDQ4Mi8zMDc4MjQ3OTAtYmM3MTY1YzktM2RjMC00OGJkLWEyMzUtMTdmMzQzM2FkMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA2NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ODc4NzhkY2ViMDBkYjYxZDBhNjY4Nzg3OTM4NTNhNGFkZDY2ZTQ1Y2E0MjdjMzU4ZGYwYTUzMTBjMzExYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.21Mf7PuF59om9l-Y1DcEAoOjVXIzkcOJgufa-Onis2M)
> 
> 笑死我是678

那不应该啊，我这里用Luminol测试也没有问题... ?_?
服务端版本和插件列表贴一下？

**Comment by xiaoluofa** [comment]
java.lang.NullPointerException: null
[15:26:51 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:51 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:51 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:51 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:51 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:51 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:52 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:52 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:53 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:54 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:55 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:55 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:55 INFO]: BellKKSK issued server command: /co i
[15:26:57 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
[15:26:59 ERROR]: Could not pass event PlayerInteractEvent to FeatherMorph v1.0.7
java.lang.NullPointerException: null
我把插件复制到另一个端，可以正常工作。但是我这个端却不行，那可能是插件兼容出了问题。

**Comment by xiaoluofa** [comment]
我看看能不能找到哪一个插件出了问题，不过挺难的，70多个插件

**Comment by MATRIX-feather** [comment]
Fixed in 1.0.10
